name: Latest blog posts
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  blogs:
    name: Update the blog articles on my GitHub profile
    runs_on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in website articles
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.alasdairmacrae.co.uk/blog/rss.xml"
          comment_tag_name: "BLOG-LIST"
